# Generated by Django 5.2.7 on 2025-10-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "worker", "verbose_name_plural": "workers"},
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
